### ISSUE TITLE
Stupid question; how do I run this myself?

### ISSUE THREAD

**Issue by VerstreuteSeele** [aspenluxxxy/DreamSimulator#5]
Hey there! beautiful project. Just wondering how I could run it on my own machine. so far I couldnt figure it out

**Comment by aspenluxxxy** [comment]
1. `pnpm i`
2. `rollup -c` or something

**Comment by VerstreuteSeele** [comment]
thx. sadly doesnt run on my pi bc wasm doesnt support linux-arm and im getting a weird error on windows with the husky package. welp. 

nice project tho! especially liking the note in your html file!
